apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-pipeline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@gitea.internal-git.svc.cluster.local:22/phong/etl-lab-gitops.git
    targetRevision: main
    path: apps/logging-pipeline
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
