apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-lb-config
  namespace: logging
data:
  nginx.conf: |
    worker_processes auto;
    events { worker_connections 1024; }

    stream {
      upstream dhcp_pool {
        least_conn;
        server rsyslog-vector-svc.logging.svc.cluster.local:65021;
      }
      upstream dns_pool {
        least_conn;
        server rsyslog-vector-svc.logging.svc.cluster.local:65022;
      }
      upstream firewall_pool {
        least_conn;
        server rsyslog-vector-svc.logging.svc.cluster.local:65023;
      }
      upstream auth_pool {
        least_conn;
        server rsyslog-vector-svc.logging.svc.cluster.local:65024;
      }
      upstream system_pool {
        least_conn;
        server rsyslog-vector-svc.logging.svc.cluster.local:65025;
      }

      server {
        listen 65021;
        proxy_pass dhcp_pool;
        proxy_timeout 30s;
        proxy_connect_timeout 5s;
      }
      server {
        listen 65022;
        proxy_pass dns_pool;
        proxy_timeout 30s;
      }
      server {
        listen 65023;
        proxy_pass firewall_pool;
        proxy_timeout 30s;
      }
      server {
        listen 65024;
        proxy_pass auth_pool;
        proxy_timeout 30s;
      }
      server {
        listen 65025;
        proxy_pass system_pool;
        proxy_timeout 30s;
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-lb
  template:
    metadata:
      labels:
        app: nginx-lb
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        ports:
        - containerPort: 65021
        - containerPort: 65022
        - containerPort: 65023
        - containerPort: 65024
        - containerPort: 65025
      volumes:
      - name: config
        configMap:
          name: nginx-lb-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-svc
  namespace: logging
spec:
  type: NodePort
  selector:
    app: nginx-lb
  ports:
  - name: dhcp
    port: 65021
    nodePort: 30021
  - name: dns
    port: 65022
    nodePort: 30022
  - name: firewall
    port: 65023
    nodePort: 30023
  - name: auth
    port: 65024
    nodePort: 30024
  - name: system
    port: 65025
    nodePort: 30025
