apiVersion: v1
kind: Namespace
metadata:
  name: hello
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-index
  namespace: hello
data:
  index.html: |
    <html>
      <body style="font-family: sans-serif">
        <h1>Hei fra GitOps 👋</h1>
        <p>Deployet via ArgoCD + Gitea SSH</p>
        <p>Timestamp: V2</p>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          volumeMounts:
            - name: webroot
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: webroot
          configMap:
            name: hello-index
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: hello
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80

